# Generated by Django 4.2.2 on 2023-10-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=100)),
            ],
            options={
                'db_table': 'Hello',
            },
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('idEmploi', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_postulation', models.DateField()),
                ('date_expiration', models.DateField()),
                ('duree_offre', models.CharField(max_length=50)),
                ('genre_demande', models.CharField(max_length=50)),
                ('intervalle_age', models.CharField(max_length=20)),
                ('localisation', models.CharField(max_length=100)),
                ('montant_paiement', models.CharField(max_length=250)),
                ('image_emploi', models.ImageField(null=True, upload_to='emplois/')),
                ('experience', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Ben Arous', 'Ben Arous'), ('Manouba', 'Manouba'), ('Nabeul', 'Nabeul'), ('Zaghouan', 'Zaghouan'), ('Bizerte', 'Bizerte'), ('Béja', 'Béja'), ('Jendouba', 'Jendouba'), ('Kef', 'Kef'), ('Siliana', 'Siliana'), ('Kairouan', 'Kairouan'), ('Sousse', 'Sousse'), ('Monastir', 'Monastir'), ('Mahdia', 'Mahdia'), ('Sfax', 'Sfax'), ('Kasserine', 'Kasserine'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Gabès', 'Gabès'), ('Medenine', 'Medenine'), ('Tataouine', 'Tataouine'), ('Gafsa', 'Gafsa'), ('Tozeur', 'Tozeur'), ('Kebili', 'Kebili')], max_length=20)),
                ('type_emploi', models.CharField(choices=[('Court', 'Court'), ('Moyen', 'Moyen'), ('Durable', 'Durable')], max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='emploi.categorie')),
            ],
            options={
                'db_table': 'emploi',
            },
        ),
    ]
