# Generated by Django 4.2.11 on 2024-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0003_delete_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='image_emploi',
            field=models.ImageField(blank=True, null=True, upload_to='emplois/'),
        ),
    ]
