# Generated by Django 4.2.2 on 2023-10-27 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Abonnement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iapremium',
            name='key',
            field=models.OneToOneField(default=0, limit_choices_to={'typeAbon': 'iapremium'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Abonnement.abonnement'),
        ),
        migrations.AddField(
            model_name='classique',
            name='key',
            field=models.OneToOneField(default=0, limit_choices_to={'typeAbon': 'classic'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Abonnement.abonnement'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='user',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL),
        ),
    ]
