# Generated by Django 4.2.2 on 2023-10-27 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('identifiant', models.CharField(default='123', max_length=255)),
                ('numero_telephone', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('societe', 'Societe'), ('employeur', 'Employeur Individuel'), ('candidat', 'Candidat'), ('admin', 'Admin')], max_length=20)),
                ('nationalite', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='societe', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('slogan', models.TextField(blank=True, max_length=30, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('secteur', models.CharField(max_length=100)),
                ('best', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RatingSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratecommunication', models.IntegerField(default=0, null=True)),
                ('rateenvironementdutravail', models.IntegerField(default=0, null=True)),
                ('ratecroissanceprofessionnelle', models.IntegerField(default=0, null=True)),
                ('rateremuneration', models.IntegerField(default=0)),
                ('ratecomportementethique', models.IntegerField(default=0)),
                ('rateculturediverse', models.IntegerField(default=0)),
                ('ratesatisfactionglobale', models.IntegerField(default=0)),
                ('ratemoyenne', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(max_length=100, null=True)),
                ('statut', models.CharField(choices=[('vérifié', 'Vérifié'), ('pas vérifié', 'Pas Vérifié')], default='pas vérifié', max_length=20)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_given_by_candidat', to=settings.AUTH_USER_MODEL)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_givento_societe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratecommunication', models.IntegerField(default=0, null=True)),
                ('rateponctualite', models.IntegerField(default=0, null=True)),
                ('rateprofessionnalisme', models.IntegerField(default=0, null=True)),
                ('ratecorrespondancecompetence', models.IntegerField(default=0)),
                ('ratequalitedutravail', models.IntegerField(default=0)),
                ('ratecooperation', models.IntegerField(default=0)),
                ('rateresolutionprobleme', models.IntegerField(default=0)),
                ('rateadaptabilite', models.IntegerField(default=0)),
                ('ratesatisfactionglobale', models.IntegerField(default=0)),
                ('ratemoyenne', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(max_length=100, null=True)),
                ('statut', models.CharField(choices=[('vérifié', 'Vérifié'), ('pas vérifié', 'Pas Vérifié')], default='pas vérifié', max_length=20)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidat_ratings', to=settings.AUTH_USER_MODEL)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societe_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personne', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=50)),
                ('titreduprofil', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(choices=[('homme', 'homme'), ('femme', 'femme'), ('autre', 'autre')], default='homme', max_length=20)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('competences', models.ManyToManyField(blank=True, to='users.competence')),
            ],
        ),
    ]
