name: CI/CD Pipeline

on:
  push:
    branches: [ "version11", "version22", "version33" ]
  pull_request:
    branches: [ "master" ]

jobs:
  continuous_integrate:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # If necessary, you can copy files directly using 'rsync' without the need for SSH
      - name: Transfer all project files
        run: rsync -avz --exclude '.git/' ./ ${{ secrets.AGENT_DIRECTORY }}

      # Debug directory structure (optional)
      - name: Debug directory structure
        run: |
          ls -R

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push Docker images for backend
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mohamedamineblibech/backend:latest
          context: ./django/khedma

      # Build and push Docker images for frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mohamedamineblibech/frontend:latest
          context: ./reactjs/khedma

  continuos_deployment:
    needs: continuous_integrate
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      # Deployment steps can be executed directly on the agent
      - name: Execute Deployment
        run: |
          cd ${{ secrets.AGENT_DIRECTORY }}
          sudo docker-compose down
          sudo docker-compose up --build -d
